
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-02T11:29:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "78dee3d03fd6027804588fd204df06b2ac57d7d3",
 "version": "0.34.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
