
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1878a451c347253eb9cfb852152a57e88f2ae848",
 "version": "2.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
