
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-01T16:30:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cdeea385d637f2121c397af64f900504c05b798",
 "version": "3.18.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
